### ISSUE TITLE
setup commands don't work on windows

### ISSUE THREAD

**Issue by jadh4v** [floryst/CustomVolViewTemplate#7]
Initial setup commands as noted in the README fail on windows in both git-bash and windows terminal.
Possible fix is to look at how os-specific paths are being handled in the template scripts.
Might be worth looking into [lungair-web-application](https://github.com/KitwareMedical/lungair-web-application) if it was fixed there.

```
npm install && npmr run setup-project
```

```
npm ERR! code UNKNOWN
npm ERR! syscall mkdir
npm ERR! path C:\Users\shreeraj.jadhav\AppData\Local\npm-cache\_cacache\index-v5\0e\e7
npm ERR! errno -4094
npm ERR! UNKNOWN: unknown error, mkdir 'C:\Users\shreeraj.jadhav\AppData\Local\npm-cache\_cacache\index-v5\0e\e7'
```

**Comment by floryst** [comment]
I'll look into this once I get it set up on a windows machine.

**Comment by floryst** [comment]
#8 should help fix this issue
